# Generated by Django 3.2.25 on 2024-09-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240926_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
